FROM ros:noetic

RUN apt-get update && apt-get -y --quiet --no-install-recommends install \
    build-essential \
    wget \
    git \
    cmake \
    python3-catkin-tools \
    mesa-utils \
    python3-pip \
    ros-noetic-mavros \
    ros-noetic-mavros-extras \
    ros-noetic-gazebo-ros \
    ros-noetic-gazebo-ros-pkgs \
    ros-noetic-cv-bridge \
    ros-noetic-tf2-geometry-msgs \
    ros-noetic-image-geometry \
    ros-noetic-tf2-tools \
    ros-noetic-vision-msgs \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install ultralytics dill pyrr shapely matplotlib
RUN pip3 install -U numpy

# Create and setup user
RUN adduser --disabled-password --gecos '' docker && \
    adduser docker sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER docker

# Create ROS workspace
WORKDIR /home/docker
RUN mkdir -p ws/src
WORKDIR ws/src
ENV ROS_WORKSPACE=/home/docker/ws
RUN catkin init

WORKDIR $ROS_WORKSPACE

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["/bin/bash"]