FROM dustynv/ros:noetic-pytorch-l4t-r35.3.1
RUN pip install ultralytics --no-deps
RUN pip install py-cpuinfo scipy seaborn tqdm thop matplotlib

RUN sudo apt-get update && sudo apt-get install guvcview git libssl-dev libusb-1.0-0-dev pkg-config libgtk-3-dev udev libgl1-mesa-dev libglu1-mesa-dev -y
RUN sudo apt remove opencv-* -y
RUN sudo apt install ros-noetic-catkin ros-noetic-cv-bridge ros-noetic-tf ros-noetic-diagnostic-updater libeigen3-dev ros-noetic-realsense2-camera -y
RUN sudo apt install ros-noetic-mavros -y


RUN curl https://raw.githubusercontent.com/IntelRealSense/librealsense/master/config/99-realsense-libusb.rules \
    -o /etc/udev/rules.d/99-realsense-libusb.rules
RUN sudo /opt/ros/noetic/lib/mavros/install_geographiclib_datasets.sh

RUN mkdir -p /home/user/ws/src
WORKDIR /home/user/ws