real_world: false

figure_collector:
  group_num_instances: 7
  group_dist_thresh: 1.5
  use_local_coords: true

nn_model_path: nn_models/n_20ep.pt
color_detection_config_file: config/color_detection_sim.json 
figure_operations: config/figure_operations.yaml

#additional settings
upload_data: true